// Generated by scripts/import-github-repos.mjs. Do not edit by hand.
export const importedProjects = [
  {
    "name": "soar-lite",
    "description": "SOAR-Lite: Alert Enrichment & Auto-Triage Engine for Elastic SIEM",
    "href": "https://github.com/mahmoudahmed3132/soar-lite",
    "language": "Python",
    "stars": 0,
    "fork": false,
    "updatedAt": "2026-04-27T19:10:41Z",
    "tags": [
      "Python"
    ]
  },
  {
    "name": "detection-gap-analyzer",
    "description": "Detection Gap Analyzer: ATT&CK coverage gap analysis with HTML heatmap for Elastic SIEM",
    "href": "https://github.com/mahmoudahmed3132/detection-gap-analyzer",
    "language": "Python",
    "stars": 0,
    "fork": false,
    "updatedAt": "2026-04-27T19:10:26Z",
    "tags": [
      "Python"
    ]
  },
  {
    "name": "canary-deception-mesh",
    "description": "Canary/Deception Mesh: honeypots, canary tokens, and near-zero FP deception sensors",
    "href": "https://github.com/mahmoudahmed3132/canary-deception-mesh",
    "language": "Python",
    "stars": 0,
    "fork": false,
    "updatedAt": "2026-04-27T19:10:07Z",
    "tags": [
      "Python"
    ]
  },
  {
    "name": "mahmoudahmed3132.github.io",
    "description": "Public GitHub repository.",
    "href": "https://github.com/mahmoudahmed3132/mahmoudahmed3132.github.io",
    "language": "HTML",
    "stars": 0,
    "fork": false,
    "updatedAt": "2026-04-26T16:10:52Z",
    "tags": [
      "HTML"
    ]
  },
  {
    "name": "vigil",
    "description": "SOC-AI",
    "href": "https://github.com/mahmoudahmed3132/vigil",
    "language": "Code",
    "stars": 0,
    "fork": true,
    "updatedAt": "2026-04-15T19:17:56Z",
    "tags": []
  },
  {
    "name": "ClaudePenTEST",
    "description": "The most autonomous pentesting AI on the market. MCP server + Python agents with 150+ security tools, exploit chaining, and PoC validation.",
    "href": "https://github.com/mahmoudahmed3132/ClaudePenTEST",
    "language": "Code",
    "stars": 0,
    "fork": true,
    "updatedAt": "2026-04-06T15:24:47Z",
    "tags": []
  },
  {
    "name": "smart-messaging-app",
    "description": "Public GitHub repository.",
    "href": "https://github.com/mahmoudahmed3132/smart-messaging-app",
    "language": "Java",
    "stars": 0,
    "fork": false,
    "updatedAt": "2023-05-17T16:52:02Z",
    "tags": [
      "Java"
    ]
  },
  {
    "name": "Ai-cei",
    "description": "Ai Chess Game ",
    "href": "https://github.com/mahmoudahmed3132/Ai-cei",
    "language": "Python",
    "stars": 0,
    "fork": false,
    "updatedAt": "2023-05-14T17:32:47Z",
    "tags": [
      "Python"
    ]
  }
] as const;
